-- Creates USA database 
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
-- CRETES table in USA database
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.states(id INT AUTO_INCREMENT UNIQUE NOT NULL, name VARCHAR(256) NOT NULL, PRIMARY KEY(id));
